name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login docker regsitry
      run: docker login -u zlzforever -p ${{ secrets.DOCKER_USER_PASSWORD }}    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zlzforever/security-token-service
    - name: Publish the Docker image
      run: docker push zlzforever/security-token-service      
